version: '3.9'

services:
  frontend:
    build:
      context: ./client
      args:
        VITE_HTTP_URL: ${VITE_HTTP_URL}
        VITE_WS_URL: ${VITE_WS_URL}
    container_name: queue-frontend

    ports:
      - "5176:80"
    restart: unless-stopped
  backend:
    build: ./server
    container_name: queue-backend
    ports:
      - "4002:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped